### ISSUE TITLE
How to install on alpine ?

### ISSUE THREAD

**Issue by RodolpheGohard** [GoogleCloudPlatform/gcsfuse#543]
Hello,

I had this dockerfile which worked a while ago:

```Dockerfile
FROM golang:1.12-alpine
RUN apk add --no-cache git
ENV GOPATH /go
RUN go get -u github.com/googlecloudplatform/gcsfuse

FROM postgres:9.6-alpine
RUN apk add --no-cache ca-certificates fuse bash && rm -rf /tmp/*
COPY --from=0 /go/bin/gcsfuse /usr/local/bin
WORKDIR /

COPY *.sh ./
RUN chmod +x *.sh

ENTRYPOINT ["/bin/sh"]
```

And suddenly it spotted working at line `RUN go get -u github.com/googlecloudplatform/gcsfuse` with the following error:

```
# github.com/googlecloudplatform/gcsfuse/internal/gcsx
src/github.com/googlecloudplatform/gcsfuse/internal/gcsx/monitoring_bucket.go:108:38: time.Since(start).Milliseconds undefined (type time.Duration has no field or method Milliseconds)
# github.com/googlecloudplatform/gcsfuse/internal/fs/wrappers
src/github.com/googlecloudplatform/gcsfuse/internal/fs/wrappers/error_mapping.go:38:5: undefined: errors.As
src/github.com/googlecloudplatform/gcsfuse/internal/fs/wrappers/error_mapping.go:43:5: undefined: errors.Is
src/github.com/googlecloudplatform/gcsfuse/internal/fs/wrappers/error_mapping.go:54:5: undefined: errors.As
src/github.com/googlecloudplatform/gcsfuse/internal/fs/wrappers/monitoring.go:84:39: time.Since(start).Milliseconds undefined (type time.Duration has no field or method Milliseconds)
```

I do not know any go language, so I'm know sure what this command does. I guess it downloads the latest sources from master and use it as a dependency.

So my questions are:
* Is there a way to target a specific branch / tag / release for which go get will work ?
* Any other way to install gcsfuse, especially on Alpine ? I've read https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md but it only provides rpm or deb

**Comment by RodolpheGohard** [comment]
More details:

I've tried using golang:1.13-alpine as the docs on install requires go 1.13, but then I run into the issue described in https://github.com/GoogleCloudPlatform/gcsfuse/issues/530


I've also tried to extract the binary from the deb file and use it in alpine but it doesn't help either:
```
# download
curl -L -O https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v0.32.0/gcsfuse_0.32.0_amd64.deb

# unpack
ar x gcsfuse_0.32.0_amd64.deb
tar xzf data.tar.gz

# Copy
cp usr/bin/gcsfuse /usr/local/bin

/go # ls -l /usr/local/bin/
total 20080
-rwxr-xr-x    1 root     root      20559378 Jul  2 14:44 gcsfuse
/go # /usr/local/bin/gcsfuse 
/bin/sh: /usr/local/bin/gcsfuse: not found
```

**Comment by RodolpheGohard** [comment]
Another note: it works with golang 1.15:

```
FROM golang:1.15-alpine3.14
RUN apk add --no-cache git
ENV GOPATH /go
RUN go get -u github.com/googlecloudplatform/gcsfuse

FROM postgres:9.6-alpine
RUN apk add --no-cache ca-certificates fuse bash && rm -rf /tmp/*
COPY --from=0 /go/bin/gcsfuse /usr/local/bin
WORKDIR /

COPY *.sh ./
RUN chmod +x *.sh

ENTRYPOINT ["/bin/sh"]
```

I guess the version requirement has not been update in `installing.md`

Still, it is not a satisfaying solution as it will break in the future, because it relies on the master which is moving. I'd really like to have a stable solution there

**Comment by lezh** [comment]
You may refer to https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/Dockerfile for building gcsfuse on alpine.
