### ISSUE TITLE
lease/read_proxy.go:165: undefined: io.CopyBuffer

### ISSUE THREAD

**Issue by cleepdar** [GoogleCloudPlatform/gcsfuse#102]
I get the following error now when I run a standard install sequence:

    $ go get github.com/googlecloudplatform/gcsfuse
    # github.com/googlecloudplatform/gcsfuse/lease
    go/src/github.com/googlecloudplatform/gcsfuse/lease/read_proxy.go:165: undefined: io.CopyBuffer

Looking at lease/read_proxy.go:165 it seems the problem was introduced with commit acf3f579db59d5825baf5899603174e472160d2f

My environment is go version go1.4.2 linux/amd64 on Centos 6.6

**Comment by jacobsa** [comment]
Thanks for the report. The [installation process](https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/docs/installing.md) changed awhile back; it now requires Go from tip rather than Go 1.4. Unless you have a specific reason to build from source, you're best off installing a release binary:

```
sudo yum install wget fuse
wget https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v0.5.0/gcsfuse_v0.5.0_linux_amd64.tar.gz
sudo tar -C /usr/local/bin -zxf gcsfuse_v0.5.0_linux_amd64.tar.gz
```
